spring.application.name: TheCountryNeighboursTour
spring.security.oauth2.client.registration:
  google:
    clientId: 86722349989-mg45u76056vmibs5j14dbb4r8f5elkcm.apps.googleusercontent.com
    clientSecret: XryhO8Hh1T11CxXTFQV823B3
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 1000
    countries:
      name: "restcountries.eu"
      url: "https://restcountries.eu/rest/v2"
    exchangerates:
      name: "api.exchangeratesapi.io"
      url: "https://api.exchangeratesapi.io/latest"
