spring.application.name: TheCountryNeighboursTour
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 1000
    countries:
      name: "restcountries.eu"
      url: "https://restcountries.eu/rest/v2"
    exchangerates:
      name: "api.exchangeratesapi.io"
      url: "https://api.exchangeratesapi.io/latest"
